ARG VARIANT="18-buster"
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-${VARIANT}

RUN apt-get update && apt-get upgrade -y

RUN corepack enable && corepack prepare pnpm@latest --activate
